### ISSUE TITLE
Multiple plugins or one?

### ISSUE THREAD

**Issue by toolmantim** [buildkite/docker-compose-buildkite-plugin#1]
We can roll this all into the one plugin…

```yml
steps:
  - agents:
      queue: docker-builder
    plugins:
      toolmantim/docker-compose:
        build-and-push:
          build-container: app
    
  - waiter

  - command: test.sh
    parallelism: 25
    agents:
      queue: docker-compose
    plugins:
      toolmantim/docker-compose:
        command-container: app
```

or split it out into two:

```yml
steps:
  - agents:
      queue: docker-builder
    plugins:
      toolmantim/docker-compose-builder:
        build-container: app
    
  - waiter

  - command: test.sh
    parallelism: 25
    agents:
      queue: docker-compose
    plugins:
      toolmantim/docker-compose:
        command-container: app
```

There'd have to be shared knowledge of what build meta-data key to look for to find the name of the built image… and both agents would need to ensure they have the correct docker credentials. But it'd split up the code, simplify the config, and force us to make image name that docker compose uses a public API (in case you wanted to pre-build the images some other way.
